[settings]
# player turn start time
players_start_time = 30
# percent of not spent time add to next turn (or round if reveal)
global_rate = 0.5
# restriction in seconds. If player move too quick additional time not count
extra_time_restriction = 5
# added seconds to the start of each new round
round_rate = 3